# fly.toml app configuration file generated for corgi-ai on 2023-10-24T18:55:54+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "corgi-ai"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 5173
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
